#!name=Nicegram解锁会员
#!desc=解锁Premium
# 微信公众号：Nature369
# 贡献者：@deezertidal

[Script]
Nicegram会员=type=http-request,pattern=^https?:\/\/restore-access\.indream\.app\/restoreAccess\?id=\w+$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/Nicegram/Script/Nicegram.js,script-update-interval=0
[MITM]
hostname= %APPEND% restore-access.indream.app

