#!name=Zhihu+
#!desc=去广告|部分VIP内容
# Author by：@WeiRen0
# 微信公众号：Nature369
# 说明： QuantumultX重写 移植 Shadowrocket模块


[URL Rewrite]

^http[s]?:\/\/api\.zhihu\.com\/commercial_api\/launch_v2 - reject-dict
^http[s]?:\/\/api\.zhihu\.com\/commercial_api\/real_time_launch_v2 - reject-dict

[Script]

zhihu7_9 = type=http-response, pattern=^http[s]?:\/\/api\.zhihu\.com\/(people\/self|unlimited\/go\/my_card|sku\/reversion_sku_ext).*$, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/WeiRen0/Scripts/main/zhihu7.js, timeout=60, script-update-interval=0

shukan2_10 = type=http-request, pattern=^http[s]?:\/\/.*zhihu\.(com|cn)\/(appview\/v2\/answer|remix-web\/paid_columns|km_player\/album|market\/paid_column|appview\/p|api\/v3\/books|books|market\/paid_magazine).*$, script-path=https://raw.githubusercontent.com/WeiRen0/Scripts/main/shukan2.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% *1*1*,125.77.176*,27.148*,183.204*,122.224*,60.188.72*,120.220*,120.222*,103.41.167.236,150.109.91*,*.zhihu.*
